### ISSUE TITLE
Yarn package to install

### ISSUE THREAD

**Issue by yashwin** [bigtestjs/mirage#7]
Is this the yarn package for this repo - https://www.npmjs.com/package/@bigtest/mirage?

**Comment by cowboyd** [comment]
Yes, that is correct, you can add this to your project with:

```js
yarn add -D @bigtest/mirage
```

**Comment by yashwin** [comment]
I meant https://yarnpkg.com/en/package/@bigtest/mirage.

Please update it in

https://yarnpkg.com/en/package/@bigtest/mirage
https://www.npmjs.com/package/@bigtest/mirage

It still directs to https://github.com/thefrontside/bigtest

**Comment by taras** [comment]
How do we update those? I assumed that this would come from package.json but there is no mention of the old repository in package.json file.
