### ISSUE TITLE
Example for GET request

### ISSUE THREAD

**Issue by yashwin** [bigtestjs/mirage#8]
Hey,

Is possible to give an example implementation of adding a `get` request to the server in react similar to `this.get('/users/:id', 'user');` in Ember. Also it would be helpful if you can tell me where should my `mirage` folder reside. Please note this is not for testing purpose. I want to deploy a site with fake data(similar to ember-mirage)

**Comment by cowboyd** [comment]
Your best bet is to have a look at this project https://github.com/folio-org/ui-eholdings/tree/master/test/bigtest and how mirage is configured there. It is to do exactly as you suggest.

**Comment by cowboyd** [comment]
There are some great examples at https://miragejs.com/docs Check them out!
